name: test

on:
  pull_request:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    name: "test"
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: test
        run: |
          echo  ${{ github.event.pull_request.head.ref }}
